Repository NewSpring/ApollosProject, pull requests merged in 2019-11, with the labels that each got.

#360 Release 1.2.0
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/package.json
  packages/apollos-church-api/src/data/content-items/__tests__/resolvers.tests.js
  packages/apollos-data-prayer/package.json
  packages/newspringchurchapp/apollos.json
  packages/newspringchurchapp/package.json
  packages/newspringchurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/ScriptureTab.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/getScripture.js
  packages/newspringchurchapp/src/content-single/Features/ScriptureFeature.js
  packages/newspringchurchapp/src/content-single/getContentItem.js
  packages/newspringchurchapp/src/scripture/ScriptureConnected.tests.js
  packages/newspringchurchapp/src/scripture/__snapshots__/ScriptureConnected.tests.js.snap
  packages/newspringchurchapp/src/scripture/getScripture.js
  packages/newspringchurchapp/src/scripture/index.js
  packages/newspringchurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/index.js
  packages/newspringchurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/index.js
  packages/newspringchurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/newspringchurchapp/src/ui/ContentCardConnected/index.js
  packages/newspringchurchapp/src/ui/SearchCard/SearchCard.tests.js
  packages/newspringchurchapp/src/ui/SearchCard/__snapshots__/SearchCard.tests.js.snap
  packages/newspringchurchapp/src/ui/SearchCard/index.js
  packages/newspringchurchapp/src/ui/WebBrowser/Browser.js
  packages/newspringchurchapp/src/user-settings/Locations/MapView.js
  yarn.lock
Labels: ready for review

#362 (DEV-4190) Fixes Save Prayer Function
  packages/apollos-data-prayer/src/prayer-requests/resolver.js
Labels: merge

#354 (DEV-3958) Adds Series and Title to Notes
  packages/apollos-church-api/src/data/content-items/data-source.js
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/SermonNotes.stories.js
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/SermonNotes.tests.js
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/__snapshots__/SermonNotes.tests.js.snap
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/index.js
  packages/newspringchurchapp/src/content-single/Features/getContentItemFeatures.js
  packages/newspringchurchapp/src/content-single/Features/index.js
Labels: ready for review

#359 (DEV-4182) Uses Nickname for Prayers
  packages/apollos-data-prayer/src/prayer-requests/data-source.js
  packages/apollos-data-prayer/src/prayer-requests/resolver.js
  packages/apollos-data-prayer/src/prayer-requests/schema.js
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerForm/AddPrayerFormConnected.js
  packages/newspringchurchapp/src/prayer/PrayerSingle/index.js
  packages/newspringchurchapp/src/prayer/SaveButton/index.js
  packages/newspringchurchapp/src/prayer/data/mutations/addPrayer.js
  packages/newspringchurchapp/src/prayer/data/mutations/savePrayer.js
  packages/newspringchurchapp/src/prayer/data/mutations/unSavePrayer.js
  packages/newspringchurchapp/src/prayer/data/queries/getCampusPrayers.js
  packages/newspringchurchapp/src/prayer/data/queries/getGroupPrayers.js
  packages/newspringchurchapp/src/prayer/data/queries/getPrayers.js
  packages/newspringchurchapp/src/prayer/data/queries/getSavedPrayers.js
  packages/newspringchurchapp/src/prayer/data/queries/getUserPrayers.js
Labels: ready for review

#364 (DEV-4205) Fixes Speaker Queries
  packages/apollos-church-api/src/data/content-items/data-source.js
Labels: ready for review

#363 (DEV-4204) Adds Extra Line to Notes
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/index.js
Labels: ready for review

#365 Release 1.2.1
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/package.json
  packages/apollos-data-prayer/package.json
  packages/newspringchurchapp/android/app/build.gradle
  packages/newspringchurchapp/apollos.json
  packages/newspringchurchapp/package.json
  packages/newspringchurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/newspringchurchapp/src/content-feed/getContentFeed.js
  packages/newspringchurchapp/src/content-single/HorizontalContentFeed/getHorizontalContent.js
  packages/newspringchurchapp/src/content-single/getContentItem.js
  packages/newspringchurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/getLikedContent.js
  packages/newspringchurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/getContentChannels.js
  packages/newspringchurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/newspringchurchapp/src/tabs/home/getCampaignContentItem.js
  packages/newspringchurchapp/src/tabs/home/getUserFeed.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/index.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/query.js
  packages/newspringchurchapp/src/ui/LikeContentButtonConnected/updateLikedContent.js
  packages/newspringchurchapp/src/ui/SearchCard/index.js
  packages/newspringchurchapp/src/user-settings/Locations/MapView.js
  packages/newspringchurchapp/src/user-settings/Locations/index.js
  yarn.lock
Labels: ready for review

#361 Optimizes Saving Prayers
  packages/newspringchurchapp/src/prayer/PrayerList/index.js
  packages/newspringchurchapp/src/prayer/SaveButton/index.js
  packages/newspringchurchapp/src/prayer/data/mutations/savePrayer.js
  packages/newspringchurchapp/src/prayer/data/mutations/unSavePrayer.js
  packages/newspringchurchapp/src/prayer/data/queries/getSavedPrayers.js
Labels: ready for review

#369 Hides Errors
  packages/newspringchurchapp/.env.production
Labels: ready for review

#370 [DEV-4211] Release 1.2.2
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-data-prayer/package.json
  packages/newspringchurchapp/apollos.json
  packages/newspringchurchapp/package.json
  packages/newspringchurchapp/src/content-single/UniversalContentItem/index.js
  yarn.lock
Labels: ready for review

#371 chore: Adds Mergify
  .mergify.yml
Labels: merge

#374 Removes Mergify
  .mergify.yml
Labels: merge

#368 [DEV-4210] Add Staff News to the For Staff section of the Home Feed
  packages/apollos-church-api/config.yml
  packages/newspringchurchapp/android/app/src/main/AndroidManifest.xml
  packages/newspringchurchapp/src/content-single/WeekendContentItem/index.js
  packages/newspringchurchapp/src/tabs/discover/DiscoverFeed/index.js
  packages/newspringchurchapp/src/tabs/home/Features/index.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
Labels: blocked, ready for review

#384 Upgrades to Apollos 1.2.3
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/package.json
  packages/apollos-data-prayer/package.json
  packages/newspringchurchapp/android/app/build.gradle
  packages/newspringchurchapp/apollos.json
  packages/newspringchurchapp/ios/newspringchurchapp-tvOS/Info.plist
  packages/newspringchurchapp/ios/newspringchurchapp-tvOSTests/Info.plist
  packages/newspringchurchapp/ios/newspringchurchapp/Info.plist
  packages/newspringchurchapp/ios/newspringchurchappTests/Info.plist
  packages/newspringchurchapp/package.json
  packages/newspringchurchapp/src/Providers.js
  packages/newspringchurchapp/src/client/index.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/SermonNotes.tests.js
  packages/newspringchurchapp/src/content-single/MediaControls/getContentMedia.js
  packages/newspringchurchapp/src/content-single/MediaControls/index.js
  packages/newspringchurchapp/src/content-single/WeekendContentItem/index.js
  packages/newspringchurchapp/src/content-single/getContentItem.js
  packages/newspringchurchapp/src/live/LiveButton.js
  packages/newspringchurchapp/src/live/LiveButton.tests.js
  packages/newspringchurchapp/src/live/LiveContext.js
  packages/newspringchurchapp/src/live/__snapshots__/LiveButton.tests.js.snap
  packages/newspringchurchapp/src/live/getLiveContent.js
  packages/newspringchurchapp/src/live/getLiveStream.js
  packages/newspringchurchapp/src/live/index.js
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerForm/__snapshots__/AddPrayerForm.tests.js.snap
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerForm/__snapshots__/AddPrayerFormConnected.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/newspringchurchapp/src/testing-control-panel/ChangeLivestream.js
  packages/newspringchurchapp/src/testing-control-panel/index.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
  packages/newspringchurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  packages/newspringchurchapp/src/user-settings/Locations/MapView.js
  packages/newspringchurchapp/src/user-settings/__snapshots__/ChangePassword.tests.js.snap
  packages/newspringchurchapp/src/user-settings/__snapshots__/PersonDetails.tests.js.snap
  yarn.lock
Labels: merge

#372 [DEV-4176] Add App Image
  packages/apollos-church-api/src/data/content-items/data-source.js
Labels: ready for review

#382 Fixes Communicator Bug
  packages/apollos-church-api/src/data/content-items/resolver.js
  packages/apollos-church-api/src/data/content-items/schema.js
Labels: ready for review

#386 [DEV-4237] Make search no longer experimental
  packages/newspringchurchapp/src/tabs/discover/Discover.js
  packages/newspringchurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
Labels: merge

#385 Deprecates old field
  packages/apollos-church-api/src/data/people/resolver.js
  packages/apollos-church-api/src/data/people/schema.js
Labels: merge

#345 (DEV-4142) Adds Forgot Password Link
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/src/data/people/resolver.js
  packages/apollos-church-api/src/data/people/schema.js
  packages/newspringchurchapp/src/index.js
Labels: merge

#375 Simplifies Discover Feed Sorting
  packages/apollos-church-api/src/data/content-items/resolver.js
Labels: merge

#387 Theming and style tweaks
  packages/apollos-church-api/src/data/content-items/data-source.js
  packages/apollos-church-api/src/data/content-items/resolver.js
  packages/newspringchurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/newspringchurchapp/src/content-single/ContentSeriesContentItem/index.js
  packages/newspringchurchapp/src/content-single/ContentSingle.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/__snapshots__/SermonNotes.tests.js.snap
  packages/newspringchurchapp/src/content-single/HorizontalContentFeed/index.js
  packages/newspringchurchapp/src/content-single/WeekendContentItem/index.js
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerForm/__snapshots__/AddPrayerForm.tests.js.snap
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerForm/__snapshots__/AddPrayerFormConnected.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/newspringchurchapp/src/tabs/home/Home.js
  packages/newspringchurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/newspringchurchapp/src/theme/theme.js
  packages/newspringchurchapp/src/ui/BrandedCard.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/contentCardComponentMapper.js
  packages/newspringchurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
  packages/newspringchurchapp/src/ui/SearchCard/__snapshots__/SearchCard.tests.js.snap
  packages/newspringchurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
Labels: merge

#388 [DEV-4238] Added Search Icon
  packages/newspringchurchapp/src/tabs/discover/index.js
Labels: merge

#391 (DEV-4171) Fixes Live Button
  packages/newspringchurchapp/src/live/LiveButton.js
  packages/newspringchurchapp/src/live/LiveContext.js
Labels: merge

#376 Better Slug Query Error Reporting
  packages/apollos-church-api/src/data/content-items/data-source.js
Labels: merge

#392 [DEV-4239] Split Content Channel Name
  packages/newspringchurchapp/src/content-single/WeekendContentItem/index.js
  packages/newspringchurchapp/src/tabs/discover/DiscoverFeed/index.js
  packages/newspringchurchapp/src/tabs/home/Features/index.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
Labels: ready for review

#395 [DEV-4191] Fix mapview to not show the Web campus
  packages/newspringchurchapp/src/user-settings/Locations/MapView.js
Labels: ready for review

#379 (DEV-3654) Adds Short Domain to Deep Link Functionality
  packages/newspringchurchapp/android/app/src/main/AndroidManifest.xml
  packages/newspringchurchapp/ios/newspringchurchapp/newspringchurchapp.entitlements
Labels: merge

#393 [DEV-4241] Home Feed Feature Updates
  packages/apollos-church-api/config.yml
  packages/newspringchurchapp/src/tabs/home/Features/getFeedFeatures.js
  packages/newspringchurchapp/src/tabs/home/Features/index.js
Labels: blocked

#396 (DEV-4222) Adds Tracking to Prayer
  packages/newspringchurchapp/src/index.js
  packages/newspringchurchapp/src/prayer/PrayerList/index.js
  packages/newspringchurchapp/src/prayer/PrayerSingle/index.js
  packages/newspringchurchapp/src/prayer/SaveButton/index.js
Labels: ready for review

#394 (DEV-4203) Fixes Prayer View on Small Phones
  packages/newspringchurchapp/src/prayer/PrayerMenu.js
  packages/newspringchurchapp/src/prayer/PrayerTabView/index.js
Labels: ready for review

#356 (DEV-4080) Removes Email from Staff Login
  packages/apollos-church-api/src/data/auth/data-source.js
  packages/apollos-church-api/src/data/auth/index.js
  packages/apollos-church-api/src/data/index.js
Labels: ready for review

#390 Revert "Removes Mergify"
  .mergify.yml
Labels: ready for review

#398 Update Join Group Link
  packages/newspringchurchapp/src/tabs/connect/ActionBar.js
Labels: merge, ready for review

#399 Prayer Redesign
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerCard/AddPrayerCard.js
  packages/newspringchurchapp/src/prayer/AddPrayer/AddPrayerCard/__snapshots__/AddPrayerCard.tests.js.snap
  packages/newspringchurchapp/src/prayer/PrayerMenu.js
  packages/newspringchurchapp/src/prayer/PrayerMenuCard/__snapshots__/PrayerMenuCard.tests.js.snap
  packages/newspringchurchapp/src/prayer/PrayerMenuCard/index.js
  packages/newspringchurchapp/src/prayer/PrayerMenuTileImage/index.js
  packages/newspringchurchapp/src/prayer/PrayerTabView/PrayerTab.js
  packages/newspringchurchapp/src/prayer/PrayerTabView/__snapshots__/PrayerTab.tests.js.snap
Labels: ready for review

#400 (DEV-4261) Adds Series Info to Content API
  packages/apollos-church-api/src/data/content-items/data-source.js
  packages/apollos-church-api/src/data/content-items/resolver.js
  packages/apollos-church-api/src/data/content-items/schema.js
Labels: ready for review

#402 (DEV-4261) Adds Sermon Series to API
  packages/apollos-church-api/src/data/content-items/data-source.js
  packages/apollos-church-api/src/data/content-items/resolver.js
  packages/apollos-church-api/src/data/content-items/schema.js
Labels: ready for review

#405 Fixes Mergify
  .mergify.yml
Labels: ready for review

#403 (DEV-4258) Adds Thumbnails to Videos API
  packages/apollos-church-api/src/data/content-items/data-source.js
  packages/apollos-church-api/src/data/content-items/schema.js
Labels: ready for review

#407 fix: Adds Safety Check
  packages/apollos-church-api/src/data/content-items/data-source.js
Labels: merge

#408 Fixes Mergify Title Check
  .mergify.yml
Labels: merge

#404 Adds Week Number to Notes
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/SermonNotes.tests.js
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/__snapshots__/SermonNotes.tests.js.snap
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/index.js
  packages/newspringchurchapp/src/content-single/Features/getContentItemFeatures.js
  packages/newspringchurchapp/src/content-single/Features/index.js
Labels: merge

#406 chore: Add Series Index to Horizontal Content Items
  packages/newspringchurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/newspringchurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/newspringchurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
  packages/newspringchurchapp/src/ui/ContentCardConnected/query.js
  packages/newspringchurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
Labels: merge

#409 fix: Removes Videos from some content
  packages/apollos-church-api/src/data/content-items/data-source.js
Labels: merge

#410 chore: Removed Pills from Horizontal Content Cards
  packages/newspringchurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
Labels: ready for review

#411 chore: (DEV-4255) Adds Sermon Thumbnails
  packages/newspringchurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/newspringchurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/newspringchurchapp/src/ui/ContentCardConnected/query.js
  packages/newspringchurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
Labels: merge

#413 chore: Upgrades to Apollos 1.2.4
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/package.json
  packages/apollos-church-api/src/data/content-items/data-source.js
  packages/apollos-data-prayer/package.json
  packages/newspringchurchapp/apollos.json
  packages/newspringchurchapp/package.json
  packages/newspringchurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/ContentTab.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/ScriptureTab.js
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/newspringchurchapp/src/content-single/DevotionalContentItem/index.js
  packages/newspringchurchapp/src/content-single/HTMLContent/index.js
  packages/newspringchurchapp/src/event/Event.js
  packages/newspringchurchapp/src/event/__snapshots__/Event.tests.js.snap
  packages/newspringchurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
  packages/newspringchurchapp/src/scripture/__snapshots__/ScriptureConnected.tests.js.snap
  packages/newspringchurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/newspringchurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/newspringchurchapp/src/user-settings/Locations/index.js
  yarn.lock
Labels: merge

#397 fix: (DEV-4250) Removes Duplicate Copyrights from Sermon Notes
  packages/apollos-church-api/config.yml
  packages/newspringchurchapp/src/content-single/Features/SermonNotes/index.js
Labels: merge

#377 chore: Use ESV as Default
  packages/apollos-church-api/config.yml
Labels: merge

#415 chore: Updated Give Link
  packages/newspringchurchapp/src/tabs/connect/ActionBar.js
Labels: merge, ready for review

#416 chore: (DEV-4265) Adds Some BugSnag Config
  packages/apollos-church-api/src/bugsnag.js
  packages/apollos-church-api/src/data/campuses/data-source.js
  packages/newspringchurchapp/src/bugsnag.js
Labels: merge

#419 chore: Removes Development Error Logging
  packages/newspringchurchapp/src/bugsnag.js
Labels: merge

#420 chore: Removes Labels from Production
  packages/newspringchurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
Labels: merge

#422 release: 7.5.10
  packages/newspringchurchapp/CHANGELOG.md
  packages/newspringchurchapp/android/app/build.gradle
  packages/newspringchurchapp/ios/newspringchurchapp-tvOS/Info.plist
  packages/newspringchurchapp/ios/newspringchurchapp-tvOSTests/Info.plist
  packages/newspringchurchapp/ios/newspringchurchapp.xcodeproj/project.pbxproj
  packages/newspringchurchapp/ios/newspringchurchapp/Info.plist
  packages/newspringchurchapp/ios/newspringchurchappTests/Info.plist
  packages/newspringchurchapp/package.json
  packages/newspringchurchapp/src/bugsnag.js
  packages/newspringchurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
Labels: ready for review

#414 style: Improves Prayer Code Syntax
  packages/apollos-data-prayer/src/prayer-requests/data-source.js
Labels: merge

#421 fix: Removes Unneccesary iOS Config
  packages/newspringchurchapp/ios/newspringchurchapp/Info.plist
Labels: merge

#418 chore: Removes Prayer Package
  packages/apollos-church-api/package.json
  packages/apollos-church-api/src/data/authMock.js
  packages/apollos-church-api/src/data/campusMock.js
  packages/apollos-church-api/src/data/index.js
  packages/apollos-church-api/src/data/prayer-menu-categories/data-source.js
  packages/apollos-church-api/src/data/prayer-menu-categories/index.js
  packages/apollos-church-api/src/data/prayer-menu-categories/resolver.js
  packages/apollos-church-api/src/data/prayer-menu-categories/schema.js
  packages/apollos-church-api/src/data/prayer-requests/__tests__/__snapshots__/resolver.test.js.snap
  packages/apollos-church-api/src/data/prayer-requests/__tests__/data-source.test.js
  packages/apollos-church-api/src/data/prayer-requests/__tests__/resolver.test.js
  packages/apollos-church-api/src/data/prayer-requests/data-source.js
  packages/apollos-church-api/src/data/prayer-requests/index.js
  packages/apollos-church-api/src/data/prayer-requests/resolver.js
  packages/apollos-church-api/src/data/prayer-requests/schema.js
  packages/apollos-data-prayer/.babelrc
  packages/apollos-data-prayer/.npmignore
  packages/apollos-data-prayer/README.md
  packages/apollos-data-prayer/__mocks__/@apollosproject/config.js
  packages/apollos-data-prayer/__mocks__/apollo-server-env.js
  packages/apollos-data-prayer/package.json
  packages/apollos-data-prayer/src/followingsMock.js
  packages/apollos-data-prayer/src/index.js
  packages/apollos-data-prayer/src/sanitize-html.js
  packages/apollos-data-prayer/src/test-utils.js
  packages/apollos-data-prayer/src/utils.js
  yarn.lock
Labels: merge

#424 fix: Revert "fix: Removes Unneccesary iOS Config"
  packages/newspringchurchapp/ios/newspringchurchapp/Info.plist
Labels: merge
